In [1]:
import pymania as mn

{'MRP_F': <class 'pymania.solvers.mrp_symm_force.MRP_F'>, 'MRP_NF': <class 'pymania.solvers.mrp_symm_noforce.MRP_NF'>, 'Solver': <class 'pymania.solvers.base.Solver'>}


In [2]:
a = mn.create_project('MRP_F','test')

In [3]:
for roi in ['L'+str(xx) for xx in range(1,20)]:
    a.add_roi(roi)

In [4]:
a.add_subject(481042)

In [5]:
a.load()

In [6]:
a.run()

/anaconda2/envs/py36/lib/python3.6/site-packages/sklearn/linear_model/base.py:509: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  linalg.lstsq(X, y)


In [7]:
a.save_to_db()

ROIs: 100%|██████████| 19/19 [00:24<00:00,  1.35s/it]


In [16]:
a.

AttributeError: 'MRP_F' object has no attribute 'save'

In [6]:
a.find_noise_threshold()

In [7]:
a.find_envelope_points()
a.find_local_regressors()

/anaconda2/envs/py36/lib/python3.6/site-packages/sklearn/linear_model/base.py:509: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  linalg.lstsq(X, y)


In [8]:
a.find_corrected_weights()

In [10]:
a.subjects[481042]('L1','L3').weight

-0.6647541060587275

In [5]:
from inspect import isclass, isabstract, getmembers

In [10]:
getmembers(mn.solvers,lambda x:isclass(x))

[('ABC', abc.ABC),
 ('EnsembleST', pymania.primitives.EnsembleST),
 ('Graph', py2neo.database.Graph),
 ('LinearRegression', sklearn.linear_model.base.LinearRegression),
 ('MANIA2Error', pymania.primitives.MANIA2Error),
 ('MRP_F', pymania.solvers.mrp_symm_force.MRP_F),
 ('MRP_NF', pymania.solvers.mrp_symm_noforce.MRP_NF),
 ('Node', py2neo.types.Node),
 ('NoiseError', pymania.utils.noise.NoiseError),
 ('PairST', pymania.primitives.PairST),
 ('RegressionError', pymania.utils.regression.RegressionError),
 ('Regressor', pymania.utils.regression.Regressor),
 ('Relationship', py2neo.types.Relationship),
 ('ST', pymania.primitives.ST),
 ('Solver', pymania.solvers.base.Solver),
 ('backend', pymania.io.neo_tools.backend),
 ('tqdm', tqdm._tqdm.tqdm)]

In [4]:
mn.F.svs

{}

In [7]:
B = A()

In [9]:
type(B).name

AttributeError: type object 'A' has no attribute 'name'

In [10]:
def f():
    pass

In [14]:
f.order = 3

In [15]:
f.order

3

In [24]:
a = np.array([[1,20],[3,2],[11,-2]])
b = np.array([[8,54],[19,-3]])
c = np.vstack((a,b))
ind = np.ones((5,1))
ind[3:,0] = 2
d = np.hstack((c,ind))
d

array([[ 1., 20.,  1.],
       [ 3.,  2.,  1.],
       [11., -2.,  1.],
       [ 8., 54.,  2.],
       [19., -3.,  2.]])

In [29]:
d = sorted(d,key=lambda x:x[0])


AttributeError: 'list' object has no attribute 'reshape'

In [57]:
l=12
ind = np.ones((l,1))
ind[4:,0] = -1
ind = np.sort(ind,axis=0)
ind

array([[-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [1]:
import numpy as np

In [62]:
a[[0,2]]

array([[ 1, 20],
       [11, -2]])